site_name: Galaxy Australia Training
site_description: Tutorials for using Galaxy Australia
site_author: Anna Syme, Gareth Price, Torsten Seemann
site_favicon: favicon.ico

site_url: 'https://galaxy-au-training.github.io/tutorials/'

repo_name: 'Galaxy-Australia-training/tutorials'
repo_url: 'https://github.com/Galaxy-Au-training/tutorials'

copyright: '&copy; The authors; 2018-'

#theme: yeti
theme: material

extra:
    feature:
        tabs: true
    social:
        - type: 'coffee'
          link: ''
        - type: 'github'
          link: 'https://github.com/Galaxy-Au-training/tutorials'
        - type: 'bug'
          link: 'https://github.com/Galaxy-Au-training/tutorials/issues'


markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
    - codehilite
    - pymdownx.details
    - footnotes
extra_css:
    - css/sepsis.css

pages:
- Welcome: index.md
- Get started: modules/galaxy/index.md
- Learn key tasks: modules/intro/index.md


# - Starting with Galaxy: modules/galaxy/index.md
- Quality control: modules/fastqc/index.md
- Genome assembly: modules/spades/index.md
- Genome annotation: modules/prokka/index.md
- Variant calling - bacteria: modules/snippy/index.md
- Variant calling - human: modules/variants/index.md


# - Metagenomics: modules/metagenomics/metagenomics.md
# - Workflows - Introduction: modules/workflows/index.md
# - Workflow - Assembly and annotation: modules/workflow-assembly-annotation/index.md
# - Workflow - Variant calling: modules/workflow-variant-calling/index.md
# - Workflow - Differential gene expression: modules/workflow-rna-seq/index.md
# - Galaxy Resources: galaxy-resources.md




    # Snippy core
    # Gubbins
    #- Public data &rarr; assembly, annotation: modules/access_data/index.md
- Antibiotic-resistant genes: modules/abricate/index.md
- Using MLST: modules/mlst/index.md
    #- Viral genome sequencing: modules/viral_genomes/index.md

# - Metagenomics with FROGS: modules/frogs/index.md
- Sample identification: modules/kraken/index.md
    #- PacBio assembly with SMRT portal: modules/pacbio/index.md
    #- PacBio assembly with command line tools: modules/cmdline_assembly/index.md
    #- Spades assembly - commandline: modules/spades_cmdline/index.md
    #- Genome alignment with Mauve: modules/mauve/index.md
    #- Pangenomes with Roary/Phandango - command line: modules/roary/index.md
    #- Pangenomes with Roary/Phandango - Galaxy: modules/roary-galaxy/index.md
    #- Long read assembly workshop: modules/cmdline_assembly_v2/index.md
    #- Annotation using command line tools: modules/cmdline_prokka/index.md
    #- Bash scripts: modules/scripts/index.md

- RNA-seq - bacteria: modules/dge/index.md
- RNA-seq - humans: modules/rna-humans/index.md

- Metagenomics: modules/metagenomics/metagenomics.md

- Galaxy help & resources: modules/resources/index.md
#- Transcriptomics:
#  - Overview: modules/transcriptomics.md
#  - Dataset: modules/data-rna/index.md
#  #- Quality control: modules/fastqc/index.md
#  #- Read trimming: modules/trimmomatic/index.md
#  - Transcriptome assembly: modules/stringtie/index.md
    #- Differential gene expression using Galaxy and Degust: modules/dge/index.md
    #- Differential gene expression using Kallisto and Degust: modules/kallisto/index.md
     #- Salmon: modules/salmon/index.md
#- Advanced:
    #- Differential Gene Expression: intro/dge/index.md
    #- Pan genome: intro/roary/index.md
    #- Artemis: modules/artemis/index.md
    #- JBrowse: modules/jbrowse/index.md

#- Proteomics:
    #- Protein Identification: modules/xtandem/index.md
    #- Pathway annotation and prediction: modules/pathway_tools/annotation/index.md

#- Metabolomics:
    #- Metabolite identification: modules/xcms/index.md
    #- Draft: modules/xcms/metab_draft.md

# - About: about/index.md
